### ISSUE TITLE
Update Wiki Enviroment Variables to reflect new default values

### ISSUE THREAD

**Issue by Godspeed-exe** [cardano-foundation/cardano-rosetta-java#228]
My recent pull request has set the default values to mainnet. Can you modify the Wiki page to reflect this?
![image](https://github.com/cardano-foundation/cardano-rosetta-java/assets/52638249/1d993fab-3af5-4bd1-934b-73753afbfa68)

**Comment by Kammerlo** [comment]
Done adjusted the wiki
