### ISSUE TITLE
Stop/restart Docker container > shutdown cardano-node gracefully 

### ISSUE THREAD

**Issue by Godspeed-exe** [cardano-foundation/cardano-rosetta-java#231]
## Why
I'm currently under the impression that the node doesn't get shutdown gracefully upon a `docker restart`  or `docker stop`.  This causes the node to (re)start significantly slower.  I still have to confirm this - waiting on mainnet sync to complete. Just dropping this here for awareness / follow up lat a later stage.

**Comment by Kammerlo** [comment]
Will be done within the Mithril branch
