### ISSUE TITLE
Warning ouput when building from source

### ISSUE THREAD

**Issue by Godspeed-exe** [cardano-foundation/cardano-rosetta-java#235]
## Context & versions
When following the 'building from source' steps, the output shows (below image). This is confusing an creates the idea that something was incorrect.

![image](https://github.com/cardano-foundation/cardano-rosetta-java/assets/52638249/00f1482e-61ad-4a1c-9cc9-bab7ac401402)

**Comment by Kammerlo** [comment]
Will be fixed within the changes for the HF. See the following commit: https://github.com/cardano-foundation/cardano-rosetta-java/pull/233/commits/5481799545af37740f23cb4a2a71edcf827a41b7
