### ISSUE TITLE
/search/transactions  endpoint not filtering for account_identifier bug

### ISSUE THREAD

**Issue by kassymkhan1** [cardano-foundation/cardano-rosetta-java#262]
Context & versions
When running '/search/transactions ', found that the 'account_identifier' field is not working, and whether I add this field or not, it will return all txs blockhain.
If the account_identifier field is populated, only txs for the specified account need to be returned

Steps to reproduce
Request body -
```
{
    "network_identifier": {
        "blockchain": "cardano",
        "network": "mainnet"
    },
    "account_identifier": {
        "address": "addr1q8ygzw3qlk5f87rll33lr6a0s6fur3f7vxwhrv3asm52rvs8p3mj7y483vtsrxnfkd452a560k4l36twavtmr0jxphasye06g9"
}
```

Actual behavior
Returning all the txs blockchain

Expected behavior
Should return only txs for address

**Comment by Kammerlo** [comment]
Hey @kassymkhan1 ,
I just checked the code. If you want to filter for `addresses` it is currently implemented to use it like this: 
`{
    "network_identifier": {
        "blockchain": "cardano",
        "network": "mainnet"
    },
        "address":  "addr1q8ygzw3qlk5f87rll33lr6a0s6fur3f7vxwhrv3asm52rvs8p3mj7y483vtsrxnfkd452a560k4l36twavtmr0jxphasye06g9"
}`

So it's using the `address` field, but I will add a check to use either of these. Checking if `address` is set, if not I'll use the address from the `account_identifier`.
